apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderitemdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderItem
  template:
    metadata:
      labels:
        app: OrderItem
    spec:
      containers:
      - name: orderitem
        image: samplectr1.azurecr.io/menuitemrepos:latestorder
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: orderitem
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: OrderItem
